//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb.Infraestructura.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoWebContainer : DbContext
    {
        public ProyectoWebContainer()
            : base("name=ProyectoWebContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entrevistas> EntrevistasSet { get; set; }
        public virtual DbSet<Usuarios> UsuariosSet { get; set; }
        public virtual DbSet<Menus> MenusSet { get; set; }
        public virtual DbSet<SubMenu> SubMenuSet { get; set; }
    }
}
